pie title Percentage of Topics by Document Types
    "Installation Guide" : 2
    "Release Notes" : 5
    "Developer Guides" : 10
	"API Reference" : 5
	"Tutorials" : 7
	"Cookbooks" : 5
	"User Guide" : 30
	"Developer Guide" : 60